version: "3.7"
services: 
    mysql:
        image: mysql:5.7
        container_name: smbsdatabase
        volumes: 
            - todo-mysql-data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todos
    api:
        image: nestjs
        container_name: smbsintranetapi
        build:
            dockerfile: Dockerfile
            context: .
            # Only will build development stage from our dockerfile
            target: development
        command: npm run start:dev
        ports: 
            - 3000:3000
            # debugging port
            - 9229:9229
        environment: 
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: todos
            NODE_ENV: development
        depends_on: 
            - mysql
volumes:
    todo-mysql-data:
        external: true